repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
  - id: ruff
    types_or: [ python, pyi, jupyter ]
    args: [--fix]
    exclude: econometricML/
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]
    exclude: econometricML/