name: integration-tests

env:
  TELEMETRY_ENABLED: false
  REFLEX_DEP: "git+https://github.com/reflex-dev/reflex@main"
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      reflex_dep:
        description: "Reflex dependency (full specifier)"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  reflex-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11' 
      - name: Install Requirements for personal_website and reflex
        run: pip install '${{ github.event.inputs.reflex_dep || env.REFLEX_DEP }}' -r env/requirements.txt
      - name: Init Website for reflex-web
        run: reflex init
      - name: Export the website
        run: reflex export